name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Rodar testes e gerar cobertura
        run: mvn -B verify

      - name: Publicar relatório dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports/

      - name: Publicar relatório de cobertura
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura
          path: target/site/jacoco/

      - name: Publicar dados para análise
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: dados-analise
          path: target/


  quality:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Cache SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Baixar dados da análise
        uses: actions/download-artifact@v4
        with:
          name: dados-analise
          path: target

      - name: Analisar no SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=SamuelModesto_TesteMeli
          -Dsonar.qualitygate.wait=true


  build:
    needs:
      - test
      - quality

    if: |
      always() &&
      needs.test.result == 'success' &&
      (needs.quality.result == 'success' || needs.quality.result == 'skipped')

    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build da aplicação
        run: mvn package -DskipTests

      - name: Publicar artifact
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao
          path: target/*.jar